#!/usr/bin/env bash

hc() {
	herbstclient "$@"
}

mod=Mod1
resize_step=0.03

hc emit_hook reload
hc unlock
hc keyunbind --all
hc mouseunbind --all
hc unrule -F
killall dzen2

hc keybind $mod-y focus left
hc keybind $mod-n focus down
hc keybind $mod-e focus up
hc keybind $mod-o focus right
hc keybind $mod-Tab cycle +1

hc keybind $mod-q close

hc keybind $mod-space \
            or , and . compare tags.focus.curframe_wcount = 2 \
                     . cycle_layout +1 horizontal vertical max grid \
               , cycle_layout +1

hc keybind $mod-Shift-y shift left
hc keybind $mod-Shift-n shift down
hc keybind $mod-Shift-e shift up
hc keybind $mod-Shift-o shift right

hc keybind $mod-Control-y resize left +$resize_step
hc keybind $mod-Control-n resize down +$resize_step
hc keybind $mod-Control-e resize up +$resize_step
hc keybind $mod-Control-o resize right +$resize_step
hc keybind $mod-k fullscreen toggle

hc keybind $mod-f split buttom 0.5
hc keybind $mod-p split explode
hc keybind $mod-u split right 0.5
hc keybind $mod-d remove

hc keybind $mod-Shift-space floating toggle

hc keybind $mod-Shift-q quit

tag_names=( 1 2 3 4 5 6 7 M B )
tag_keys=( 1 2 3 4 5 6 7 8 9 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$mod-$key" use_index "$i"
        hc keybind "$mod-Shift-$key" move_index "$i"
    fi
done

hc detect_monitors

hc pad 0 58 25 25 25
hc pad 1 58 25 25 25

for f in ~/.config/autostart/*; do
   bash $f &
   sleep 0.5
done

hc set frame_border_width 0
hc set frame_bg_active_color $(xgetres *.background_active)
hc set frame_bg_transparent 1
hc attr theme.active.color $(xgetres *.foreground)
hc attr theme.normal.color $(xgetres *.background)

hc set window_gap 7
hc set frame_padding -2

hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc attr theme.tilling.reset 1
hc attr theme.floating.reset 1
