#!/usr/bin/env bash

hc() {
	herbstclient "$@"
}

hc emit_hook reload

# Keybindings
mod=Mod1

hc keyunbind --all
hc mouseunbind --all

hc keybind $mod-Shift-q quit

# Focusing clients
hc keybind $mod-y focus left
hc keybind $mod-n focus down
hc keybind $mod-e focus up
hc keybind $mod-o focus right

hc keybind $mod-Tab cycle +1

# Moving clients
hc keybind $mod-Shift-y shift left
hc keybind $mod-Shift-n shift down
hc keybind $mod-Shift-e shift up
hc keybind $mod-Shift-o shift right

hc keybind $mod-space \
			or , and . compare tags.focus.curframe_wcount = 2 \
					 . cycle_layout +1 horizontal vertical grid max \
			   , cycle_layout +1

# Layouting
hc keybind $mod-p split explode
hc keybind $mod-d remove

resize_step=0.02
hc keybind $mod-Control-y resize left +$resize_step
hc keybind $mod-Control-n resize down +$resize_step
hc keybind $mod-Control-e resize up +$resize_step
hc keybind $mod-Control-o resize right +$resize_step
hc mousebind $mod-B1 resize

# Controlling clients
hc keybind $mod-q close
hc keybind $mod-k fullscreen toggle

# Tags
tag_names=( {1..9} )
tag_keys=( {1..9}  )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
	hc add "${tag_names[$i]}"
	key="${tag_keys[$i]}"
	if ! [ -z "$key" ] ; then
		hc keybind "$mod-$key" use_index "$i"
		hc keybind "$mod-Shift-$key" move_index "$i"
	fi
done

# Rules
hc unrule -F

hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# Theme
hc attr theme 1

hc pad 0 16 16 16 16

hc set window_gap 6
hc set frame_gap 4
hc set frame_border_width 0
hc set frame_bg_transparent 1

hc set frame_bg_active_color $(xgetres *.background_active)
hc attr theme.active.color $(xgetres *.foreground)
hc attr theme.normal.color $(xgetres *.background)
